---
language: rust
dist: trusty
sudo: required

matrix:
  include:
    # minimal supported Rust version
    - rust: 1.32.0
    - rust: stable
    - rust: beta
    - rust: nightly
      addons:
        apt:
          packages:
            # cargo-tarpaulin needs this
            - libssl-dev
      install:
        # For test coverage. In install step so that it can use cache.
        - cargo tarpaulin --version || RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  allow_failures:
    - rust: nightly

cache: cargo

script:
  - 'if [[ "$TRAVIS_RUST_VERSION" = 1.32.0 ]]; then RUSTFLAGS="-D warnings" cargo build --verbose; fi'
  - cargo build --verbose
  - cargo test --verbose
  - 'if [[ "$TRAVIS_RUST_VERSION" = nightly ]]; then cargo bench; fi'

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" = nightly ]]; then
    # Calculate test coverage
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
