---
language: rust
dist: trusty
sudo: false

matrix:
  include:
    - rust: stable
      addons:
        apt:
          packages:
            - libssl-dev
    - rust: beta
    - rust: nightly
  allow_failures:
    - rust: nightly

cache:
  cargo: true
  apt: true

script:
  - cargo build --verbose
  - cargo test --verbose
  - 'if [[ "$TRAVIS_RUST_VERSION" = nightly ]]; then cargo bench; fi'

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" = stable ]]; then
    # test coverage
    cargo install cargo-tarpaulin
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
