[package]
name = "fancy-regex"
version = "0.3.5" # remember to update html_root_url
authors = ["Raph Levien <raph@google.com>", "Robin Stocker <robin@nibor.org>"]
edition = "2018"
license = "MIT"
description = "An implementation of regexes, supporting a relatively rich set of features, including backreferences and look-around."
readme = "README.md"
repository = "https://github.com/fancy-regex/fancy-regex"
documentation = "https://docs.rs/fancy-regex"
categories = ["text-processing"]

[dependencies]
regex = "1.2" # when we go to >= 1.3.8, we can get rid of the `contains_empty` workaround, see https://github.com/rust-lang/regex/blob/master/CHANGELOG.md#138-2020-05-28
bit-set = "0.5"

[dev-dependencies]
criterion = "= 0.3.0" # pinned because 0.3.1 doesn't work on Rust 1.32
rayon-core = "= 1.7.0" # dependency of criterion, pinned to work on Rust 1.32
matches = "0.1.8"
quickcheck = "0.7"
rand = "0.5"

[[bench]]
name = "bench"
harness = false
